Release/week1
pesto-students/mock-prep-n11-eta2-fe pull request #3
Opened 2021-12-09 16:54 UTC by saifmohammed888

Week 1 tasks

Frontend setup
Backend Setup
Configure backend server (Heroku)
Configure frontend server (Netlify)
Database design and Setup
Setup CI/CD (Frontend and backend)
Landing Page
Login and Signup Backend
Login and SignUp Frontend
Admin Dashboard
Resource Page
Interviewer Onboard Page
Topics Page
Student and Interviewer Profile
Quiz
Admin Routes
Additional Pages
Additional Pages

2021-12-10 08:18 UTC, sraghudatta94 requested changes

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Admin/Dashboard.js
> +                        <p>Total Earning</p>
from const, so thatit will be easy for api integration

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Admin/Dashboard.js
> +                            <span style={{display:"flex"}}>
try to minimize inline css

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Admin/Dashboard.js
> +                                <p>{review.name}<br/>{ review.comment}</p>
code destructuring

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Common/Header/DashHeader.css
> +    width: 80.5vw;
make it consistent either % or px/em/vw

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Common/Quiz/Quiz.js
> +import { quizList,resourceFilter } from '../../../../constant/data'
absolute imports pls

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Common/Quiz/Quiz.js
> +            <DashHeader icon={<QuestionOutlined />} title="Quiz" rightComponent={<>
make an icons.js const and put it in assets folder. use that everywhere

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Common/Resource/Resource.css
> +    width:82.5vw;
remove dead code

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Interviewer/Profile/InterviewerProfile.css
> +        background-color: royalblue;
always use #

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Student/List/StudentList.js
> +                    {studentList.length > 0 ?
recheck if this is required pls

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Student/List/StudentList.js
> +                    {studentList.length > 0 ?
x?y:z

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Student/List/StudentList.js
> +                                <section key={student.id} className="listedInterviewer">
pls make this as a section component

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Student/Profile/StudentProfile.css
> +    height: auto !important;
i see important in many places in many css files. please recheck once (low priority)

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Dashboard/Student/Profile/StudentProfile.js
> +    const studentForm = JSON.parse(JSON.stringify(student));
pls check if there is a better way

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Join Us/JoinUs.js
> +                    <JoinUsButton className="sign-btn" signin={isSignUp} type={"facebook"}  />
we decided to hold fb login

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Join Us/SignIn/SignIn.js
> +                    <section className="dummyButtons">
tab view not button view pls

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Packages/Packages.js
> +                                <li key={detail}>{detail}</li>
li key should be `key`

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Primary Components/Button/MP_Button.js
> +    return <Button type={props.buttonType} onClick={props.onClick} disabled={!props.isDisabled} size = {props.size} id="mainButton" className={props.className} style={{width:props.width}}>{props.butt
always destructure functions

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Primary Components/Footer/Footer.css
> +    color:white;
Hex color code

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Primary Components/Forrm/Interviewer/InterviewerForm.js
> +                            <Form.Item key={ index} className="form-input"  name={key}  label={key.toUpperCase()}  rules={[{ required: false, message: 'Please input your username!' }]}>
Please make rules right. if possible make it to a json const and reuse here

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Primary Components/Join Us/Join Us Button.css
> +    justify-content: center;
no dead code pls

2021-12-10 08:18 UTC, sraghudatta94 commented on src/components/Primary Components/Join Us/Join Us Button.js
> +      alert("Login Clicked")
no default alerts

2021-12-17 10:32 UTC, saifmohammed888 commented
Week1 Changes
Week2 Changes

2021-12-17 10:33 UTC, merged